goods_app/urls.py
from django.urls import path, include

from goods_app import views

app_name = 'goods'
urlpatterns = [
    path('', views.AllGoods.as_view(), name='all_goods'),
    path('add_goods<int:goods_id>/', views.add_goods, name='add_goods'),
    path('sub_goods<int:goods_id>/', views.sub_goods, name='sub_goods'),
    path('clear_goods/', views.clear_goods, name='clear_goods'),
    path('settle/', views.settle, name='settle'),
    path('pay/', views.pay, name='pay'),
]

小购物车/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from goods_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.AllGoods.as_view()),
    path('favicon.ico', RedirectView.as_view(url='/static/ico1.jpg')),
    path('goods/', include('goods_app.urls')),
]


from django.conf import settings
if settings.DEBUG is False:
    from django.views import static
    from django.conf.urls import url
    urlpatterns += [url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static')]

goods_app/models.py
from django.db import models

# Create your models here.


class Goods(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True, verbose_name='商品名称')
    price = models.FloatField(null=True, verbose_name='价格')
    inventory = models.PositiveSmallIntegerField(null=False, default=0, verbose_name='库存量')
    parent = models.ForeignKey('self', null=True, on_delete=models.SET_NULL, related_name='kinds', verbose_name='所属种类')

    def __str__(self):
        return self.name

goods_app/views.py
from django.db.models import F
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.views.generic import ListView
from goods_app.models import Goods
import time
from django.db import transaction, DataError, IntegrityError
from django.views.decorators.http import require_http_methods


def _get_goods_dict(request):
    """
    根据session得到 {goods: num} 的字典
    :param request: request
    :return: goods <class: dict>
    """
    goods_dict = dict()
    for k in request.session.keys():
        if k.isdigit():
            goods = Goods.objects.get(pk=int(k))
            goods_dict[goods] = request.session[k]
    return goods_dict


def _get_total(request):
    """
    计算合计价钱
    :param request: request
    :return: total <class: int>
    """
    total = 0
    goods_dict = _get_goods_dict(request)
    for goods in goods_dict:
        total += goods.price * goods_dict[goods]
    return total


def _clear_goods_func(request):
    """
    调用此函数可清空购物车
    :param request: request
    :return: None
    """
    for k in list(request.session.keys()):
        if k.isdigit():
            del request.session[k]


def _check_goods_inventory(request):
    """
    校验商品库存
    :return: 如果库存足够能够购买，则返回空列表，否则返回库存不够的商品对象组成的列表
    """
    not_enough_goods = []
    goods_dict = _get_goods_dict(request)
    for goods in goods_dict:
        if goods.inventory < goods_dict[goods]:
            not_enough_goods.append(goods)
    return not_enough_goods


class AllGoods(ListView):
    """商品列表页"""
    template_name = 'goods/all_goods.html'
    queryset = Goods.objects.filter(parent=None)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['selected_goods'] = _get_goods_dict(self.request)
        return context


def add_goods(request, goods_id):
    """
    添加商品， 用session记录添加商品及购物车内的商品，在商品列表页展示出来
    :param goods_id: 商品id
    :return: redirect response
    """
    request.session[goods_id] = request.session.get(str(goods_id), 0) + 1
    return redirect('goods:all_goods')


def sub_goods(request, goods_id):
    """
    减少商品， 用session记录添加商品及购物车内的商品，在商品列表页展示出来
    :param goods_id: 商品id
    :return: redirect response
    """
    num = request.session.get(str(goods_id), 0)
    if num:
        if num == 1:
            del request.session[str(goods_id)]
        else:
            request.session[goods_id] = num - 1
    return redirect('goods:all_goods')


def clear_goods(request):
    """
    清空购物车
    :return: redirect response
    """
    _clear_goods_func(request)
    return redirect('goods:all_goods')


def settle(request):
    """
    结算
    :return: response
    """
    context = dict()
    context['total'] = _get_total(request)
    context['selected_goods'] = _get_goods_dict(request)
    context['not_enough_goods'] = _check_goods_inventory(request)
    return render(request, 'goods/settle.html', context)


@require_http_methods(['POST'])
@transaction.atomic
def pay(request):
    """
    支付界面
    :return: response
    """
    # 修改库存量
    goods_dict = _get_goods_dict(request)
    if request.POST['pay'] != '确认支付' or not goods_dict:
        raise Http404
    # time.sleep(10)
    try:
        with transaction.atomic():
            for goods in goods_dict:
                Goods.objects.filter(pk=goods.pk).update(inventory=F('inventory')-goods_dict[goods])
    except (DataError, IntegrityError):
        return redirect('goods:settle')
    total = _get_total(request)
    _clear_goods_func(request)
    return HttpResponse(f'支付成功({total}元),返回<a href="/goods/">商品列表</a>')

templates/goods/all_goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品页</title>
</head>
<body>

<H2>商品列表</H2>
<ul>
    {% for parent in object_list %}
        <li>{{ parent.name }}类</li>
        {% if parent.kinds.all %}
            <ul>
                {% for goods in parent.kinds.all %}
                    <li>{{ goods.name }}&nbsp;&nbsp;&nbsp;&nbsp;
                        剩{{ goods.inventory }}件&nbsp;&nbsp;&nbsp;&nbsp;
                        {{ goods.price }}元/件&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'goods:add_goods' goods_id=goods.pk %}">添加</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endfor %}
    <b>
        <br>
        <br>
        <a href="{% url 'goods:clear_goods' %}">清空购物车</a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'goods:settle' %}">去结算</a>
        <br>
        <h3>购物车内的商品：</h3>
        {% if selected_goods %}
            {#  #}
            {% for selected_good in selected_goods.items %}
                <li>{{ selected_good.0.name }}:&nbsp;&nbsp;{{ selected_good.1 }}件&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'goods:sub_goods' goods_id=selected_good.0.pk %}"><button>-</button></a>&nbsp;&nbsp;
                    <a href="{% url 'goods:add_goods' goods_id=selected_good.0.pk %}"><button>+</button></a>
                </li>
            {% endfor %}
        {% else %}
            您还没有选择商品
        {% endif %}
    </b>
</ul>


</body>
</html>

templates/goods/settle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>结算页面</title>
    <script type="text/javascript">

        var phoneWidth = parseInt(window.screen.width);

        var phoneScale = phoneWidth / 640;

        var ua = navigator.userAgent;

        if (/Android (d+.d+)/.test(ua)) {
            var version = parseFloat(RegExp.$1);

            if (version > 2.3) {
                document.write('<meta name="viewport" content="width=640, minimum-scale = ‘+phoneScale+‘, maximum-scale = ‘+phoneScale+‘, target-densitydpi=device-dpi">');
            } else {
                document.write('<meta name="viewport" content="width=640, target-densitydpi=device-dpi">');
            }

        else
            {
                document.write('<meta name="viewport" content="width=640, user-scalable=no, target-densitydpi=device-dpi">');
            }

    </script>
</head>
<body>


<br>
{% if not_enough_goods %}
    <h3>订单提交失败：</h3>
    {% for goods in not_enough_goods %}
        <li>{{ goods.name }}&nbsp;剩余{{ goods.inventory }}件</li>
    {% endfor %}
    <a href="{% url 'goods:all_goods' %}">
        <button>返回修改</button>
    </a>
{% else %}
    <h3>结算清单：</h3>
    {% if selected_goods %}
        {% for selected_good in selected_goods.items %}
            <li>{{ selected_good.0.name }}:&nbsp;&nbsp;单价{{ selected_good.0.price }}元&nbsp;&nbsp;共{{ selected_good.1 }}件&nbsp;&nbsp;
                共{% widthratio selected_good.0.price 1 selected_good.1 %}元
            </li>
        {% endfor %}
        总计{{ total }}元
        <br>
        <br>
        <b>请您尽快支付，否则商品可能被人抢走哦</b>
        <br>

        <form action="{% url 'goods:pay' %}" method="post">{% csrf_token %}
            &nbsp;&nbsp;&nbsp;&nbsp;
            <button type="submit" name="pay" value="确认支付">支付</button>
        </form>

        &nbsp;&nbsp;&nbsp;&nbsp;
        <button onclick='window.location.href="{% url 'goods:all_goods' %}"'>返回继续选购</button>

    {% else %}
        您还没有选择商品， <a href="{% url 'goods:all_goods' %}">开始选购</a>
    {% endif %}
{% endif %}


</body>
</html>